### ISSUE TITLE
More widgets examples

### ISSUE THREAD

**Issue by klimesf** [jSquirrel/nutforms-ios-client#10]

**Comment by klimesf** [comment]
<img width="592" alt="screen shot 2016-04-09 at 13 10 01" src="https://cloud.githubusercontent.com/assets/5357636/14403379/7375641e-fe54-11e5-9d44-05767b879c4b.png">

@KarelCemus první field je readonly, druhý je editovatelný

**Comment by KarelCemus** [comment]
Super!
