### ISSUE TITLE
Two forms one app

### ISSUE THREAD

**Issue by klimesf** [jSquirrel/nutforms-ios-client#9]

**Comment by klimesf** [comment]
<img width="621" alt="screen shot 2016-04-09 at 12 56 55" src="https://cloud.githubusercontent.com/assets/5357636/14403315/96b06e44-fe52-11e5-9f4d-949f713d63fb.png">
<img width="620" alt="screen shot 2016-04-09 at 12 56 47" src="https://cloud.githubusercontent.com/assets/5357636/14403316/96b0f18e-fe52-11e5-8b0a-61d76fe58933.png">
<img width="620" alt="screen shot 2016-04-09 at 12 56 39" src="https://cloud.githubusercontent.com/assets/5357636/14403317/96b62ce4-fe52-11e5-8f94-196e56164736.png">

**Comment by KarelCemus** [comment]
Moc pěkné!
